title: Mellissa Catherine
# logo:
description: I am a proactive and eager-learner individual with a strong foundation in statistical analysis, actuarial calculations and machine learning, enabling me to solve business problems utilising Microsoft Excel, R, and Python. Lately, I am interested in finding the impact of climate change towards insurance industry by conducting analysis using R.
show_downloads: true
theme: jekyll-theme-minimal
